services:
  api:
    build: .
    image: skin-disease:latest
    container_name: skin-disease-api
    volumes:
      - ./models:/app/models:z
    env_file:
      - .env
    networks:
      - private-network
  nginx:
    build: ./frontend
    image: skin-disease-nginx:latest
    container_name: skin-disease-nginx
    ports:
      - "80:80"
    networks:
      - public-network
      - private-network
    depends_on:
      - api
    environment:
      - API_HOST=api


networks:
  public-network:
    driver: bridge
    internal: false
  private-network:
    driver: bridge
    internal: true