defaults:
  - _self_
  - model: resnet18

experiment_name: 'SkinDisease'
device: 'cpu'
seed: 42

data:
  dir: "data/raw/SkinDisease"
  train_path: "data/raw/SkinDisease/train"
  test_path: "data/raw/SkinDisease/test"

  batch_size: 32
  num_workers: 4
  image_size: 224

  num_classes: 22

loss_function:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001